/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Service health (per-service, structured) and watchlist freshness.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config Endpoint
         * @description Public-safe config (no secrets).
         */
        get: operations["get_config_endpoint_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Per-title download state computed by the reconciler's snapshots.
         */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download
         * @description Add movie/series to Radarr or Sonarr via the download service.
         */
        post: operations["download_api_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Search watchlist and TMDB.
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Library
         * @description First provider to read successfully becomes the view; else partial 200.
         */
        get: operations["get_library_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Library Items
         * @description Full library as a poster wall — every Movie + Series with playback facts.
         *
         *     Phase 1: routed through :class:`LibraryService` ``all_items()`` (first
         *     provider with a meaningful result wins); no provider feature-detection.
         */
        get: operations["get_library_items_api_library_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/continue-watching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Continue Watching
         * @description In-progress titles for the Discover "Continue Watching" row.
         */
        get: operations["get_continue_watching_api_library_continue_watching_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/series/{series_id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series Episodes
         * @description Every episode of one series, with per-episode playback facts (for TV).
         */
        get: operations["get_series_episodes_api_library_series__series_id__episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/recently-watched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recently Watched
         * @description Recently *finished* titles (roadmap item 2) — via the provider capability.
         */
        get: operations["get_recently_watched_api_library_recently_watched_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/{item_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Item State
         * @description Mark an item watched/unwatched (roadmap item 2). Additive endpoint.
         */
        post: operations["set_item_state_api_library__item_id__state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Library
         * @description Browser/address-bar friendly trigger for the Jellyfin library scan (GET).
         *
         *     Mirrors the canonical ``POST /api/jobs/library_scan/run`` job so a plain GET
         *     (e.g. typing the URL) can force a scan. Returns the job result.
         */
        get: operations["scan_library_api_library_scan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quality Profiles
         * @description Get quality profiles from Radarr and Sonarr via the acquisition facade.
         */
        get: operations["get_quality_profiles_api_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plex/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plex Thumb
         * @description Proxy a Plex thumbnail so the browser can render it (token stays server-side).
         */
        get: operations["plex_thumb_api_plex_thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jellyfin/poster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jellyfin Poster
         * @description Proxy a Jellyfin item's primary image so the browser can render it.
         *
         *     Keeps the Jellyfin token/credential server-side: the browser only ever hits
         *     this same-origin /api route. Phase 1: routed through the ``LibraryService``
         *     ``get_poster`` capability (first provider able to serve it wins).
         */
        get: operations["jellyfin_poster_api_jellyfin_poster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jellyfin/backdrop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jellyfin Backdrop
         * @description Proxy a Jellyfin item's 16:9 backdrop (keyart) for rich player backdrops.
         */
        get: operations["jellyfin_backdrop_api_jellyfin_backdrop_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jellyfin/stream/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jellyfin Stream
         * @description Proxy one Jellyfin item's video to the browser for in-app playback.
         *
         *     Forwarded headers: the client's ``Range`` (so direct-play seeking works).
         *     Returned: the upstream status (``206`` for a range, ``200`` for full) plus
         *     the ``Content-Type`` / ``Accept-Ranges`` / ``Content-Range`` pass-throughs.
         *
         *     **Routing modes** (verified live against the bundled Jellyfin):
         *
         *     - ``direct`` (default) — ``Static=true`` serves the container untouched.
         *       HTTP-range seekable (``206``); the ideal path for browser-safe MP4.
         *       Jellyfin *ignores* ``AudioStreamIndex``/``MaxStreamingBitrate`` here
         *       (confirmed live), so those params are not forwarded — the pickers only
         *       take effect on a non-direct mode.
         *     - ``remux`` — copy/copy into an MP4 container (no re-encode). Needed when
         *       the container (e.g. MKV) can't be indexed up-front by the browser: the
         *       remuxed MP4 starts with ``ftyp``/``moov`` so duration + playback are
         *       correct immediately. Chunked (no byte ranges) — seek by restarting with
         *       ``start_time_ticks``.
         *     - ``transcode_audio`` — ``VideoCodec=copy`` + ``AudioCodec=aac``
         *       (video untouched, audio re-encoded) for EAC3/AC3/DTS/TrueHD tracks.
         *     - ``transcode`` — ``VideoCodec=h264`` + ``AudioCodec=aac``; honours
         *       ``max_bitrate``. Used when the video codec isn't browser-decodable
         *       (HEVC/10-bit) or the quality picker asks for a lower bitrate.
         *
         *     Non-direct streams are chunked ``200`` MP4 (``ftyp`` first): seeking is done
         *     by restarting the stream at ``start_time_ticks``, not by byte ranges.
         */
        get: operations["jellyfin_stream_api_jellyfin_stream__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jellyfin/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Jellyfin Progress
         * @description Report playback position back to Jellyfin so Watched/resume UI updates.
         *
         *     Keeps the Jellyfin credential server-side; the browser only POSTs JSON here.
         */
        post: operations["jellyfin_progress_api_jellyfin_progress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jellyfin/playback-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jellyfin Playback Info
         * @description List an item's audio + text-subtitle tracks for the player track pickers.
         */
        get: operations["jellyfin_playback_info_api_jellyfin_playback_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jellyfin/subtitle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jellyfin Subtitle
         * @description Proxy a Jellyfin **text** subtitle stream as WebVTT for the browser.
         *
         *     ``index`` is the subtitle stream's ``MediaStream.Index`` from playback-info.
         *     The ``ms``/media source falls back to the item id (single-source items), so
         *     ``/api/jellyfin/subtitle?id=<item>&ms=<source>&index=<n>`` just works.
         */
        get: operations["jellyfin_subtitle_api_jellyfin_subtitle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggest/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Add
         * @description Add a TMDB-discovered title to the watchlist as a pending entry.
         */
        post: operations["suggest_add_api_suggest_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggest/add/{tmdb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Add One
         * @description Add a single TMDB title to the watchlist as a pending entry.
         */
        post: operations["suggest_add_one_api_suggest_add__tmdb_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggest/detail/{tmdb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest Detail
         * @description Return full TMDB metadata + IMDb rating for one title (on-demand, cached).
         *
         *     Powers the card-click detail modal (IMDb rating + synopsis). Fetches fresh
         *     from TMDB on demand so the grid's /api/suggest stays light (it would
         *     otherwise need one IMDb lookup per result).
         */
        get: operations["suggest_detail_api_suggest_detail__tmdb_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest
         * @description Discover titles matching user-defined filters via TMDB.
         */
        post: operations["suggest_api_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Media
         * @description One complete, backend-derived resource for a canonical media_id.
         */
        get: operations["get_media_api_media__media_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Media Endpoint
         * @description Idempotently add a canonical media_id to the right *arr backend.
         *
         *     The canonical request path is ``request_media`` (application layer). This
         *     route only maps result states to typed HTTP responses.
         */
        post: operations["request_media_endpoint_api_media__media_id__request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watchlist
         * @description Every watchlist entry as a backend-derived §18 resource.
         */
        get: operations["get_watchlist_api_watchlist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconcile Now
         * @description Re-derive every watchlist entry's status/capabilities/watch in one pass.
         */
        post: operations["reconcile_now_api_reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Jobs
         * @description Recent job_runs most-recent-first.
         */
        get: operations["get_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Job Endpoint
         * @description Run a known job command by name and return its recorded result.
         *
         *     Supported names: ``daily_watchlist`` (recommendation generation) and
         *     ``reconcile`` (frequent status reconcile). Returns the JobResult shape.
         */
        post: operations["run_job_endpoint_api_jobs__name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcquisitionModel
         * @description Acquisition backend facts for one item (spec §18 ``acquisition``).
         */
        AcquisitionModel: {
            /** Provider */
            provider?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * CapabilitiesModel
         * @description Which user actions are available (spec §18 ``capabilities``).
         */
        CapabilitiesModel: {
            /**
             * Can Download
             * @default false
             */
            can_download: boolean;
            /**
             * Can Watch
             * @default false
             */
            can_watch: boolean;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Updated */
            updated: string;
            /** Heromode */
            heroMode: string;
            /** Rotation */
            rotation: string[];
            /** Services */
            services: {
                [key: string]: boolean;
            };
        };
        /** DownloadRequest */
        DownloadRequest: {
            /**
             * Imdbid
             * @default
             */
            imdbId: string;
            /** Tmdbid */
            tmdbId?: number | null;
            /**
             * Type
             * @default
             */
            type: string;
            /** Qualityprofileid */
            qualityProfileId?: number | null;
            /**
             * Title
             * @default
             */
            title: string;
            /** Year */
            year?: number | null;
        };
        /** DownloadResponse */
        DownloadResponse: {
            /** Ok */
            ok: boolean;
            /** State */
            state: string;
            /** Message */
            message: string;
            /** Service */
            service: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Updated */
            updated: string;
            /** Titlecount */
            titleCount: number;
            /** Services */
            services?: {
                [key: string]: boolean;
            };
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Servicedetail */
            serviceDetail?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** ItemStateRequest */
        ItemStateRequest: {
            /**
             * Watched
             * @default true
             */
            watched: boolean;
        };
        /**
         * JellyfinProgressRequest
         * @description Playback progress reported by the in-app player (Jellyfin Sessions API).
         *
         *     ``event`` maps to a Jellyfin session endpoint: ``start`` -> /Sessions/Playing,
         *     ``timeupdate`` -> /Sessions/Playing/Progress, ``stopped`` -> /Sessions/Playing/Stopped.
         *     ``position_ticks`` is in Jellyfin 10ms ticks (seconds * 1e7).
         */
        JellyfinProgressRequest: {
            /**
             * Item Id
             * @default
             */
            item_id: string;
            /**
             * Position Ticks
             * @default 0
             */
            position_ticks: number;
            /**
             * Is Paused
             * @default false
             */
            is_paused: boolean;
            /**
             * Event
             * @default timeupdate
             */
            event: string;
            /**
             * Play Method
             * @default DirectPlay
             */
            play_method: string;
        };
        /**
         * JobRunResponse
         * @description One row from the job_runs table (spec Phase 13/14).
         */
        JobRunResponse: {
            /** Jobname */
            jobName: string;
            /** Startedat */
            startedAt?: string | null;
            /** Completedat */
            completedAt?: string | null;
            /**
             * Status
             * @default
             */
            status: string;
            /**
             * Itemsprocessed
             * @default 0
             */
            itemsProcessed: number;
            /** Error */
            error?: string | null;
        };
        /**
         * JobsResponse
         * @description GET /api/jobs — recent job_runs most-recent-first.
         */
        JobsResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobRunResponse"][];
        };
        /** LibraryResponse */
        LibraryResponse: {
            /** Provider */
            provider: string | null;
            /** Available */
            available: boolean;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Recent */
            recent: {
                [key: string]: unknown;
            }[];
            /** Server */
            server: string | null;
            /** Urls */
            urls?: {
                [key: string]: string;
            } | null;
        };
        /**
         * MediaResponse
         * @description The canonical single-item object the frontend renders from (§18).
         *
         *     The frontend must NOT reconstruct status/capabilities from scattered
         *     fields — this is one complete, backend-derived resource.
         */
        MediaResponse: {
            /** Id */
            id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Year */
            year?: number | null;
            /**
             * Type
             * @default
             */
            type: string;
            /**
             * Status
             * @default
             */
            status: string;
            capabilities?: components["schemas"]["CapabilitiesModel"];
            /** Watch */
            watch?: {
                [key: string]: components["schemas"]["WatchEntryModel"];
            };
            acquisition?: components["schemas"]["AcquisitionModel"] | null;
            /** Detail */
            detail?: string | null;
            /** Progress */
            progress?: number | null;
            /** Speed */
            speed?: number | null;
            /** Eta */
            eta?: number | null;
            /** Qbitstate */
            qbitState?: string | null;
            /** Qbitname */
            qbitName?: string | null;
        };
        /** QualityProfileResponse */
        QualityProfileResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
        };
        /** QualityProfilesResponse */
        QualityProfilesResponse: {
            /** Radarr */
            radarr: components["schemas"]["QualityProfileResponse"][];
            /** Sonarr */
            sonarr: components["schemas"]["QualityProfileResponse"][];
        };
        /**
         * ReconcileResponse
         * @description POST /api/reconcile — re-derive every entry's snapshot in one pass.
         */
        ReconcileResponse: {
            /** Ok */
            ok: boolean;
            /** Entries */
            entries: components["schemas"]["MediaResponse"][];
            /** Indexerissue */
            indexerIssue?: string | null;
        };
        /**
         * RequestMediaResponse
         * @description Outcome of POST /api/media/{media_id}/request (§15 vocab).
         */
        RequestMediaResponse: {
            /** Ok */
            ok: boolean;
            /** State */
            state: string;
            /** Message */
            message: string;
            /**
             * Mediaid
             * @default
             */
            mediaId: string;
            /**
             * Service
             * @default
             */
            service: string;
            /** Candidates */
            candidates?: {
                [key: string]: unknown;
            }[];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Watchlist */
            watchlist: components["schemas"]["SearchResult"][];
            /** Tmdb */
            tmdb: components["schemas"]["SearchResult"][];
            /** Tmdbkey */
            tmdbKey: boolean;
            /** Servicesdown */
            servicesDown: boolean;
        };
        /** SearchResult */
        SearchResult: {
            /** Title */
            title: string;
            /** Year */
            year: number | null;
            /** Type */
            type: string;
            /** Imdbid */
            imdbId: string;
            /** Tmdbid */
            tmdbId: number | null;
            /** Poster */
            poster: string;
            /** Inwatchlist */
            inWatchlist: boolean;
            /** Director */
            director: string;
            /** Cast */
            cast: string[];
            /** Snippet */
            snippet: string;
            /** Voteaverage */
            voteAverage?: number | null;
        };
        /** StatusEntry */
        StatusEntry: {
            /** State */
            state: string;
            /** Service */
            service: string;
            /** Detail */
            detail?: string | null;
            /** Progress */
            progress?: number | null;
            /** Speed */
            speed?: number | null;
            /** Eta */
            eta?: number | null;
            /** Qbitstate */
            qbitState?: string | null;
            /** Qbitname */
            qbitName?: string | null;
            /** Plexkey */
            plexKey?: string | null;
            /** Plexurl */
            plexUrl?: string | null;
            /** Embyurl */
            embyUrl?: string | null;
            /** Jellyfinurl */
            jellyfinUrl?: string | null;
            /** Jellyfinitemid */
            jellyfinItemId?: string | null;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Statuses */
            statuses: {
                [key: string]: components["schemas"]["StatusEntry"];
            };
            /** Indexerissue */
            indexerIssue?: string | null;
        };
        /**
         * SuggestDetail
         * @description Full TMDB detail for one suggested title (card click → detail modal).
         */
        SuggestDetail: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Id */
            id: number;
            /** Media Type */
            media_type: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Year */
            year?: number | null;
            /**
             * Overview
             * @default
             */
            overview: string;
            /** Genres */
            genres?: string[];
            /**
             * Runtime
             * @default 0
             */
            runtime: number;
            /**
             * Cert
             * @default
             */
            cert: string;
            /** Cast */
            cast?: string[];
            /**
             * Director
             * @default
             */
            director: string;
            /**
             * Tmdb Score
             * @default 0
             */
            tmdb_score: number;
            /**
             * Vote Count
             * @default 0
             */
            vote_count: number;
            /**
             * Poster
             * @default
             */
            poster: string;
            /**
             * Backdrop
             * @default
             */
            backdrop: string;
            /**
             * Imdb Id
             * @default
             */
            imdb_id: string;
            /**
             * Imdb Rating
             * @default 0
             */
            imdb_rating: number;
        };
        /**
         * SuggestRequest
         * @description User-defined filter criteria for suggest.
         */
        SuggestRequest: {
            /**
             * Media Type
             * @default all
             */
            media_type: string;
            /** Genres */
            genres?: string[];
            /** Year From */
            year_from?: number | null;
            /** Year To */
            year_to?: number | null;
            /**
             * Min Rating
             * @default 6
             */
            min_rating: number;
            /**
             * Sort By
             * @default popularity.desc
             */
            sort_by: string;
            /**
             * Count
             * @default 20
             */
            count: number;
            /**
             * Include Owned
             * @default false
             */
            include_owned: boolean;
        };
        /**
         * SuggestResponse
         * @description POST /api/suggest response.
         */
        SuggestResponse: {
            /** Results */
            results: components["schemas"]["SuggestResult"][];
            /** Total */
            total: number;
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            /** Genres Available */
            genres_available: string[];
        };
        /**
         * SuggestResult
         * @description One suggested title.
         */
        SuggestResult: {
            /** Tmdb Id */
            tmdb_id: number;
            /** Title */
            title: string;
            /** Year */
            year?: number | null;
            /** Media Type */
            media_type: string;
            /**
             * Tmdb Score
             * @default 0
             */
            tmdb_score: number;
            /**
             * Vote Count
             * @default 0
             */
            vote_count: number;
            /** Genres */
            genres?: string[];
            /**
             * Overview
             * @default
             */
            overview: string;
            /**
             * Poster
             * @default
             */
            poster: string;
            /**
             * Backdrop
             * @default
             */
            backdrop: string;
            /**
             * In Watchlist
             * @default false
             */
            in_watchlist: boolean;
            /**
             * In Library
             * @default false
             */
            in_library: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WatchEntryModel
         * @description One provider's watch link (spec §18 ``watch.<provider>``).
         */
        WatchEntryModel: {
            /**
             * Available
             * @default false
             */
            available: boolean;
            /** Url */
            url?: string | null;
            /** Error */
            error?: string | null;
            /** Item Id */
            item_id?: string | null;
            /** Played */
            played?: boolean | null;
            /** Playback Position */
            playback_position?: number | null;
            /** Runtime */
            runtime?: number | null;
        };
        /**
         * WatchlistResponse
         * @description GET /api/watchlist — every pending + recommended entry as a resource.
         */
        WatchlistResponse: {
            /** Entries */
            entries: components["schemas"]["MediaResponse"][];
            /** Indexerissue */
            indexerIssue?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_config_endpoint_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    download_api_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_library_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
        };
    };
    get_library_items_api_library_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_continue_watching_api_library_continue_watching_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_series_episodes_api_library_series__series_id__episodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recently_watched_api_library_recently_watched_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    set_item_state_api_library__item_id__state_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemStateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_library_api_library_scan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_quality_profiles_api_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityProfilesResponse"];
                };
            };
        };
    };
    plex_thumb_api_plex_thumb_get: {
        parameters: {
            query?: {
                path?: string;
                width?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jellyfin_poster_api_jellyfin_poster_get: {
        parameters: {
            query?: {
                id?: string;
                width?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jellyfin_backdrop_api_jellyfin_backdrop_get: {
        parameters: {
            query?: {
                id?: string;
                width?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jellyfin_stream_api_jellyfin_stream__item_id__get: {
        parameters: {
            query?: {
                audio_stream_index?: number;
                /** @description MaxStreamingBitrate (bps) — applied on the transcode modes; 0 = original */
                max_bitrate?: number;
                /** @description Legacy alias for mode=transcode_audio (video copied, audio → AAC) */
                transcode_audio?: boolean;
                /** @description direct (Static file, HTTP-range seekable) | remux (copy/copy → mp4) | transcode_audio (video copy + AAC) | transcode (H.264 + AAC, honours max_bitrate) */
                mode?: string;
                /** @description Start the stream at this item offset (restart-seek for non-direct modes); seconds × 1e7 */
                start_time_ticks?: number;
            };
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jellyfin_progress_api_jellyfin_progress_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JellyfinProgressRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jellyfin_playback_info_api_jellyfin_playback_info_get: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jellyfin_subtitle_api_jellyfin_subtitle_get: {
        parameters: {
            query?: {
                id?: string;
                /** @description MediaSourceId (defaults to the item id) */
                ms?: string;
                index?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_add_api_suggest_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_add_one_api_suggest_add__tmdb_id__post: {
        parameters: {
            query?: {
                media_type?: string;
            };
            header?: never;
            path: {
                tmdb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_detail_api_suggest_detail__tmdb_id__get: {
        parameters: {
            query?: {
                media_type?: string;
            };
            header?: never;
            path: {
                tmdb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_api_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_api_media__media_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_media_endpoint_api_media__media_id__request_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestMediaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_api_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
        };
    };
    reconcile_now_api_reconcile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileResponse"];
                };
            };
        };
    };
    get_jobs_api_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_job_endpoint_api_jobs__name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
