#!/usr/bin/env python3
"""Check the tvOS models and endpoints against the FROZEN API contract — on Linux, with no Mac.

    python3 apple/scripts/check-tvos-models.py
    python3 apple/scripts/check-tvos-models.py --falsify

WHY THIS EXISTS
---------------
`docs/APPLE_CLIENTS_PLAN.md` §4.3 wanted `swift-openapi-generator` to produce the tvOS types from
`docs/api/openapi.v1.json`, so there is one source of truth and no handwritten drift. That tool needs
`brew`, a SwiftPM plugin, and a script that has never been run — and none of it can be exercised from
this sandbox, where every Mac-bound artefact is *written, never executed* until a handover round.

So the types are handwritten and THIS is what keeps them honest. It is the same trade the rest of
`apple/` makes (`apple/WORKFLOW.md` §5): push the decision to where it can be RUN, and leave the
unverifiable surface as small as possible. A generated client would be verified by the generator; a
handwritten one is verified here.

WHAT IT CHECKS
--------------
R1  every model in `apple/tvos/RKMCinemaTV/Core/Models/` exists as a schema in the contract;
R2  every JSON key decoded there is a property of that schema — a mistyped key does NOT fail at
    runtime, it silently decodes to nil/0/false, which is the class of bug a TV in another room makes
    undiagnosable;
R3  every NON-optional property of a `Decodable` model is `required` in the contract or carries a
    `default` — i.e. the server has promised to send it. This is not pedantry: in this contract almost
    nothing is `required`, so `LoginResponse.user`, `ProfilesResponse.profiles`,
    `SelectProfileResponse.profile` and both of `MeResponse`'s are optional *in the contract*, and
    decoding them as non-optional would turn a server that omitted one into a decoding failure;
R4  every endpoint string literal in the tvOS sources is a real path in the contract, so a typo is a
    failed round here rather than a 404 on a TV;
R5  no `Decodable`/`Codable` type is declared OUTSIDE `Core/Models/` unless it is named in
    `NON_CONTRACT_MODELS` below with a reason — otherwise a model could be smuggled past R1-R3 by
    moving the file. (One is: FastAPI's error envelope, which the framework generates and which is not
    in the contract.)

⚠ `--falsify` REVERTS EVERY RULE ONE AT A TIME and requires the matching check to go red. A gate that
has never been seen to fail is not evidence — that lesson is in `apple/` three times over.

Exit codes: 0 clean · 1 a real failure · 2 the contract or a source file is missing.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CONTRACT = REPO / "docs" / "api" / "openapi.v1.json"
TVOS = REPO / "apple" / "tvos"
MODEL_DIR = TVOS / "RKMCinemaTV" / "Core" / "Models"

#: Types that are deliberately NOT contract schemas, with the reason. R5 fails on anything else found
#: outside `Core/Models/`, so this list is the only way a model escapes R1-R3 — and adding an entry is a
#: deliberate act with a written justification, not an omission.
NON_CONTRACT_MODELS = {
    "ErrorEnvelope": "FastAPI's error envelope is generated by the framework, not by us; it is not in "
                     "the contract and must not be invented into it (see Core/APIClient.swift).",
}


# --------------------------------------------------------------------------- Swift parsing
def strip_comments_and_strings(text: str) -> tuple[str, list[str]]:
    """Return (code with comments blanked and string literals replaced by "", the literals).

    ⚠ A naive `//`-strip corrupts a file whose string literals contain `//` — `"http://rkm-hp…"` is in
    this very tree — so the scan walks the text once, tracking string and comment state. Literals are
    collected here rather than by a regex over the raw text, because a regex cannot tell a string from
    a doc comment, and a doc comment mentioning `api/status` would then be checked as an endpoint.
    """
    out: list[str] = []
    literals: list[str] = []
    i, n = 0, len(text)
    while i < n:
        ch = text[i]
        two = text[i:i + 2]
        if two == "//":
            j = text.find("\n", i)
            i = n if j == -1 else j
            continue
        if two == "/*":
            j = text.find("*/", i + 2)
            i = n if j == -1 else j + 2
            continue
        if ch == '"':
            j = i + 1
            buf: list[str] = []
            while j < n:
                if text[j] == "\\" and j + 1 < n:
                    buf.append(text[j:j + 2])
                    j += 2
                    continue
                if text[j] == '"':
                    break
                buf.append(text[j])
                j += 1
            literals.append("".join(buf))
            # ⚠ The literal is KEPT in the code text, not blanked: `case isAdmin = "is_admin"` must still
            # read as a CodingKeys mapping (blanking it here silently downgraded every snake_case key to
            # its Swift name and made R2 fire on all of them). The walker still advances past the literal,
            # which is what keeps a `//` inside a string from being mistaken for a comment.
            out.append(text[i:j + 1])
            i = j + 1
            continue
        out.append(ch)
        i += 1
    return "".join(out), literals


def block_body(text: str, start: int) -> tuple[str, int]:
    """The brace-matched body of a declaration whose opening `{` is at or after `start`."""
    open_at = text.find("{", start)
    if open_at == -1:
        return "", len(text)
    depth = 0
    for i in range(open_at, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[open_at + 1:i], i + 1
    return text[open_at + 1:], len(text)


STRUCT_RE = re.compile(r"\bstruct\s+(\w+)\s*(?::\s*([^\{]+))?\{")
PROPERTY_RE = re.compile(r"^\s*(?:let|var)\s+(\w+)\s*:\s*([^=\n]+?)(\s*=\s*.*)?$", re.M)
CASE_RE = re.compile(r"^\s*case\s+(\w+)\s*(?:=\s*\"([^\"]*)\")?\s*$", re.M)

MODEL_CONFORMANCES = ("Decodable", "Codable", "Encodable")


def parse_models(path: Path, root: Path) -> list[dict]:
    """Every `struct` in a Swift file, with its conformances, properties and CodingKeys mapping.

    `root` is threaded through so the reported file path is relative to the tree being checked — which is
    the real repo in a normal run and a TEMP COPY under `--falsify`. (Hardcoding `REPO` here made every
    falsification run die with a `relative_to` ValueError instead of reporting a mutation.)
    """
    code, _ = strip_comments_and_strings(path.read_text(encoding="utf-8"))
    found: list[dict] = []
    for match in STRUCT_RE.finditer(code):
        name, conformances = match.group(1), (match.group(2) or "")
        body, _ = block_body(code, match.start())
        enum_at = body.find("CodingKeys")
        keys: dict[str, str] = {}
        if enum_at != -1:
            enum_body, _ = block_body(body, enum_at)
            for swift_name, json_name in CASE_RE.findall(enum_body):
                keys[swift_name] = json_name or swift_name
        props = []
        for prop_name, prop_type, _default in PROPERTY_RE.findall(body):
            if prop_name == "CodingKeys":
                continue
            # ⚠ A COMPUTED property is not decoded, and this guard is not hypothetical: `warningText`
            # in `ProfilesResponse` matched the regex on the first run and was reported as an invented
            # JSON key. A stored property's type never contains a `{`.
            if "{" in prop_type:
                continue
            props.append({
                "name": prop_name,
                "json_key": keys.get(prop_name, prop_name),
                "type": prop_type.strip(),
                "optional": prop_type.strip().endswith("?"),
            })
        found.append({
            "name": name,
            "conformances": [c.strip() for c in conformances.split(",") if c.strip()],
            "properties": props,
            "coding_key_cases": sorted(keys),
            "has_coding_keys": enum_at != -1,
            "file": str(path.relative_to(root)),
        })
    return found


# --------------------------------------------------------------------------- checks
def check(root: Path) -> tuple[list[str], list[str]]:
    """Run every rule against `root`. Returns (failures, notes)."""
    failures: list[str] = []
    notes: list[str] = []

    contract_path = root / CONTRACT.relative_to(REPO)
    if not contract_path.is_file():
        raise SystemExit(f"contract not found: {contract_path}")
    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    schemas = contract.get("components", {}).get("schemas", {})
    paths = set(contract.get("paths", {}))

    tvos = root / TVOS.relative_to(REPO)
    model_dir = root / MODEL_DIR.relative_to(REPO)
    if not model_dir.is_dir():
        raise SystemExit(f"model directory not found: {model_dir}")

    # ---- R1/R2/R3, on every file in Core/Models/
    model_files = sorted(model_dir.glob("*.swift"))
    if not model_files:
        failures.append(f"R1: no models found in {model_dir}")
    checked_keys = 0
    for path in model_files:
        for model in parse_models(path, root):
            contract_conformances = [c for c in model["conformances"] if c in MODEL_CONFORMANCES]
            if not contract_conformances:
                continue  # a plain value type, not wire data — nothing to check
            schema = schemas.get(model["name"])
            if schema is None:
                failures.append(
                    f"R1: {model['file']} declares `{model['name']}`, which is not a schema in "
                    f"{CONTRACT.name} — an invented model"
                )
                continue
            properties = schema.get("properties", {})
            required = set(schema.get("required", []))
            decoded = model["conformances"] and (
                "Decodable" in model["conformances"] or "Codable" in model["conformances"]
            )
            # ⚠ R2b — a CodingKeys case with no matching property. It compiles, and it decodes to nothing,
            # so it is invisible until someone wonders why a field is always empty: it is the residue of a
            # rename that only happened on one side. Found by falsification, not by review.
            property_names = {p["name"] for p in model["properties"]}
            for case_name in model["coding_key_cases"]:
                if case_name not in property_names:
                    failures.append(
                        f"R2b: {model['name']}'s CodingKeys declares `{case_name}`, which is not a "
                        f"property of the struct — a key nothing decodes"
                    )
            missing_from_swift = [k for k in properties if k not in {p["json_key"] for p in model["properties"]}]
            for prop in model["properties"]:
                checked_keys += 1
                if prop["json_key"] not in properties:
                    failures.append(
                        f"R2: {model['name']}.{prop['name']} decodes \"{prop['json_key']}\", which is "
                        f"not a property of that schema — it would silently decode to nil"
                    )
                    continue
                if not decoded or prop["optional"]:
                    continue
                body = properties[prop["json_key"]]
                promised = prop["json_key"] in required or "default" in body
                if not promised:
                    failures.append(
                        f"R3: {model['name']}.{prop['name']} is NON-OPTIONAL but "
                        f"\"{prop['json_key']}\" is neither required nor defaulted in the contract — "
                        f"a server that omitted it would fail the decode"
                    )
            notes.append(
                f"{model['name']:24s} {len(model['properties'])} key(s) checked"
                + (f", not decoded: {', '.join(missing_from_swift)}" if missing_from_swift else "")
            )

    # ---- R4, endpoint literals anywhere in the tvOS sources
    endpoints = 0
    for path in sorted(tvos.rglob("*.swift")):
        _, literals = strip_comments_and_strings(path.read_text(encoding="utf-8"))
        for literal in literals:
            if not literal.startswith("api/"):
                continue
            endpoints += 1
            if "/" + literal not in paths:
                failures.append(
                    f"R4: {path.relative_to(root)} uses \"{literal}\", which is not a path in "
                    f"{CONTRACT.name}"
                )

    # ---- R5, wire types hiding outside Core/Models/
    outside = 0
    for path in sorted(tvos.rglob("*.swift")):
        if path.parent == model_dir:
            continue
        for model in parse_models(path, root):
            if not any(c in ("Decodable", "Codable") for c in model["conformances"]):
                continue
            if model["name"] in NON_CONTRACT_MODELS:
                notes.append(f"{model['name']:24s} exempt — {NON_CONTRACT_MODELS[model['name']]}")
                continue
            outside += 1
            failures.append(
                f"R5: {model['file']} declares `{model['name']}: Decodable` OUTSIDE Core/Models/ — it "
                f"is not covered by R1-R3. Move it, or add it to NON_CONTRACT_MODELS with a reason."
            )

    notes.append(f"{len(model_files)} model file(s), {checked_keys} key(s), {endpoints} endpoint "
                 f"literal(s), {outside} unchecked wire type(s)")
    if not endpoints:
        failures.append("R4: no endpoint literals were found at all — the scan is looking at nothing")
    return failures, notes


# --------------------------------------------------------------------------- falsify
MUTATIONS = [
    ("R2 a mistyped JSON key",
     "RKMCinemaTV/Core/Models/AuthModels.swift",
     'case isAdmin = "is_admin"', 'case isAdmin = "isadmin"'),
    ("R2 an invented field",
     "RKMCinemaTV/Core/Models/AuthModels.swift",
     'case warning\n    }', 'case warning\n        case nope = "nope"\n    }'),
    ("R3 an optional read as non-optional",
     "RKMCinemaTV/Core/Models/AuthModels.swift",
     "let user: SessionUser?", "let user: SessionUser"),
    ("R1 an invented model",
     "RKMCinemaTV/Core/Models/AuthModels.swift",
     "struct LoginResponse: Decodable {", "struct LoginResponses: Decodable {"),
    ("R4 a mistyped endpoint",
     "RKMCinemaTV/Server/ServerProbe.swift",
     'appendingPathComponent("api/status")', 'appendingPathComponent("api/stauts")'),
    ("R5 a wire type outside Models/",
     "RKMCinemaTV/Debug/DebugHUD.swift",
     "struct DebugHUD: View {", "struct Sneaky: Decodable { let a: String }\n\nstruct DebugHUD: View {"),
]


def falsify() -> int:
    print("falsification — each rule reverted one at a time, each must go RED\n")
    baseline_failures, _ = check(REPO)
    if baseline_failures:
        print("✗ the tree is ALREADY failing — fix it before falsifying:")
        for line in baseline_failures:
            print("   ", line)
        return 1
    print("baseline: clean\n")

    survivors = 0
    with tempfile.TemporaryDirectory() as tmp:
        tmp_root = Path(tmp)
        for label, rel, old, new in MUTATIONS:
            shutil.rmtree(tmp_root / "apple", ignore_errors=True)
            shutil.rmtree(tmp_root / "docs", ignore_errors=True)
            (tmp_root / "docs" / "api").mkdir(parents=True, exist_ok=True)
            shutil.copy2(CONTRACT, tmp_root / "docs" / "api" / CONTRACT.name)
            shutil.copytree(REPO / "apple" / "tvos", tmp_root / "apple" / "tvos")

            target = tmp_root / "apple" / "tvos" / rel
            text = target.read_text(encoding="utf-8")
            if old not in text:
                print(f"✗ {label}: the mutation no longer applies — `{old[:40]}…` not found in {rel}")
                survivors += 1
                continue
            target.write_text(text.replace(old, new, 1), encoding="utf-8")

            failures, _ = check(tmp_root)
            if failures:
                print(f"✓ {label}: RED — {failures[0][:96]}…")
            else:
                print(f"✗ {label}: SURVIVED (still green) — the check does not cover it")
                survivors += 1

    print()
    if survivors:
        print(f"FAIL — {survivors} mutation(s) survived; the gate is not proving what it claims.")
        return 1
    print(f"PASS — {len(MUTATIONS)}/{len(MUTATIONS)} mutations went RED, each on its own rule.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--falsify", action="store_true",
                        help="revert each rule once and require the check to fail")
    args = parser.parse_args()

    if args.falsify:
        return falsify()

    failures, notes = check(REPO)
    print("tvOS models vs the frozen contract (docs/api/openapi.v1.json)\n")
    for note in notes:
        print(f"  · {note}")
    print()
    if failures:
        print(f"FAIL — {len(failures)} problem(s):\n")
        for line in failures:
            print(f"  ✗ {line}")
        return 1
    print("PASS — every model key, endpoint and optionality matches the contract.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
