import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import RKMServerKit

/// The transport for every native call this app makes — one place where a request is built, sent,
/// decoded and logged.
///
/// ⚠⚠ **WHY THIS FILE IS PURE FOUNDATION, AND WHAT THAT BUYS.** `apple/WORKFLOW.md` §5: there is no
/// Apple SDK in the sandbox, so anything that lives only on the Mac is *written, never executed* until
/// a handover round — and a handover round is the most expensive thing in this workflow. `URLSession`
/// exists on Linux through `FoundationNetworking`, so this file is **compiled and typechecked here**
/// (`apple/scripts/check-apple-typecheck.sh`) and its wire format is checked against the frozen contract
/// (`apple/scripts/check-tvos-models.py`) before it ever reaches the Mac. What is left for the Mac is
/// the views — which is the smallest possible unverifiable surface.
///
/// ⚠ **There is NO API client in `apple/ios/` to copy from, deliberately** — the iOS app is a
/// `WKWebView` shell and the page makes its own same-origin `/api` calls. This is the first one, and it
/// is a client of the *contract*, not of the frontend's TypeScript types.
enum APIError: Error, LocalizedError, Equatable {

    /// A transport failure: DNS, refused connection, TLS, timeout. ⚠ Only these mean "unreachable" —
    /// see `ServerProbe` for the same rule applied to the status check.
    case transport(String)
    /// An HTTP response the server chose to send. It IS the server answering, which is the distinction
    /// that matters: a `401` here must never be reported as "can't reach the server".
    case http(status: Int, message: String, authProblem: String?)
    case decoding(String)

    var errorDescription: String? {
        switch self {
        case .transport(let detail):
            return detail.isEmpty ? "Could not reach the server." : "Could not reach the server. \(detail)"
        case .http(let status, let message, _):
            return message.isEmpty ? "The server answered \(status)." : message
        case .decoding(let detail):
            return "The server's answer could not be read. \(detail)"
        }
    }

    /// ⚠ The 401 taxonomy is the SERVER's (`backend/api/session.py`): a marked 401 means *"switch
    /// profile"*, never *"sign out"*. Collapsing the two here would be a security decision made in the
    /// wrong layer — the server already distinguishes an expired session from a refused credential.
    var isUnauthorized: Bool {
        if case .http(let status, _, _) = self { return status == 401 }
        return false
    }

    /// The header the server sets on a marked 401 (`X-RKM-Auth-Problem`). Surfaced, never interpreted.
    var authProblem: String? {
        if case .http(_, _, let problem) = self { return problem }
        return nil
    }
}

/// ⚠ Not a contract schema, and deliberately declared here rather than in `Core/Models/`: FastAPI's
/// error envelope is generated by the framework, not by us, so it is not in `docs/api/openapi.v1.json`
/// and it must not be invented into it. `check-tvos-models.py` knows about this exemption by scanning
/// only `Core/Models/` for contract types — and reports every `Decodable` it finds *outside* that
/// folder, so a model cannot be smuggled past the check by moving the file.
struct ErrorEnvelope: Decodable {
    let detail: String
}

struct APIClient {

    let address: ServerAddress
    var timeout: TimeInterval

    init(address: ServerAddress, timeout: TimeInterval = 20) {
        self.address = address
        self.timeout = timeout
    }

    // MARK: - Verbs

    func get<T: Decodable>(_ path: String, correlation: CorrelationID = .next()) async throws -> T {
        let data = try await perform(method: "GET", path: path, body: nil, correlation: correlation)
        return try decode(data, path: path, correlation: correlation)
    }

    /// A GET with query parameters — `GET /api/jellyfin/detail?id=…`.
    ///
    /// ⚠⚠ **THIS OVERLOAD EXISTS BECAUSE OF A MEASURED TRAP, not for tidiness.** The no-query path below is
    /// built with `URL.appendingPathComponent(_:)`, which **percent-escapes its whole argument**: appending
    /// `"api/jellyfin/detail?id=X"` produces `…/detail%3Fid=X`, i.e. the query becomes part of the PATH and
    /// the server answers `404` for an item that exists. (`PosterURL`'s header records the same trap for the
    /// poster proxy, which is why that file has its own builder.) So a parameterised request goes through
    /// `URLComponents`, where each VALUE is escaped as data and a `+`, `&` or `/` inside an id cannot split
    /// the query.
    ///
    /// ⚠ The path literal itself stays free of the query (`"api/jellyfin/detail"`), which is what lets R4 in
    /// `check-tvos-models.py` match it against the contract's path list EXACTLY rather than having to
    /// tolerate a suffix.
    func get<T: Decodable>(_ path: String, query: [URLQueryItem],
                           correlation: CorrelationID = .next()) async throws -> T {
        let data = try await perform(method: "GET", path: path, query: query, body: nil,
                                     correlation: correlation)
        return try decode(data, path: path, correlation: correlation)
    }

    func post<T: Decodable, Body: Encodable>(_ path: String, body: Body,
                                             correlation: CorrelationID = .next()) async throws -> T {
        let data = try await perform(method: "POST", path: path, body: try encode(body), correlation: correlation)
        return try decode(data, path: path, correlation: correlation)
    }

    /// ⚠ For the routes that answer **`204 No Content`** — `POST /api/auth/logout` does. A `204` is
    /// SUCCESS with no body, and decoding it into `T` would report a working sign-out as a decoding
    /// failure. (The same `204` rule the frontend learned on `POST /api/jellyfin/progress`.)
    func postIgnoringBody(_ path: String, correlation: CorrelationID = .next()) async throws {
        _ = try await perform(method: "POST", path: path, body: nil, correlation: correlation)
    }

    /// The body-carrying twin of the call above — `POST /api/jellyfin/progress` and
    /// `POST /api/jellyfin/subtitle-disable` both take JSON and answer `204`/a body nobody needs.
    ///
    /// ⚠⚠ **IT IS NOT A CONVENIENCE OVERLOAD: it is the only shape that lets a WRITE be issued without a
    /// DECODE.** Decoding a `204` into `T` would report a saved position as a decoding failure — the
    /// exact bug the no-body version above exists for. ⚠ And a `2xx` here is still not evidence the write
    /// landed (`PlaybackStore` re-reads the position).
    func postIgnoringBody<Body: Encodable>(_ path: String, body: Body,
                                           correlation: CorrelationID = .next()) async throws {
        _ = try await perform(method: "POST", path: path, body: try encode(body),
                              correlation: correlation)
    }

    // MARK: - Internals

    private func encode<Body: Encodable>(_ body: Body) throws -> Data {
        do {
            return try JSONEncoder().encode(body)
        } catch {
            // A request-body encoding failure is a bug in THIS app, not a server problem, so it is
            // reported as such rather than sent as an empty body the server would answer 422 to.
            throw APIError.decoding("could not encode a \(Body.self) request body: \(error)")
        }
    }

    private func decode<T: Decodable>(_ data: Data, path: String, correlation: CorrelationID) throws -> T {
        do {
            return try JSONDecoder().decode(T.self, from: data)
        } catch {
            RKMLog.error("could not decode \(T.self) from \(path): \(error)", category: .net, correlation: correlation)
            throw APIError.decoding("\(T.self): \(error)")
        }
    }

    /// The one place a request exists. Every line below is logged — including the failures, because a
    /// missing log line is an undiagnosable bug when the app runs on a TV in another room.
    private func perform(method: String, path: String, query: [URLQueryItem] = [], body: Data?,
                         correlation: CorrelationID) async throws -> Data {
        // ⚠ Relative to the STORED address, which is the origin — the same reason the page's own `/api`
        // calls need no CORS change. Nothing here knows a host: it comes from the address a human typed.
        //
        // ⚠⚠ The builder lives in `Core/RequestURL.swift` rather than here, and that is the point: this file
        // imports `RKMServerKit`, so nothing in it can be executed in the sandbox. The one rule in the
        // transport that fails SILENTLY — a query turned into part of the path by
        // `appendingPathComponent(_:)` — is therefore in a `Foundation`-only file that
        // `check-tvos-core.py` compiles AND runs.
        guard let url = RequestURL.url(base: address.url, path: path, query: query) else {
            throw APIError.transport("could not build the request URL for \(path)")
        }

        var request = URLRequest(url: url)
        request.httpMethod = method
        request.timeoutInterval = timeout
        // ⚠ Always revalidate: this app has no business serving a stale session list off a disk cache,
        // and the session cookie is what decides the answer.
        request.cachePolicy = .reloadIgnoringLocalCacheData
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        if let body {
            request.httpBody = body
            request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        }

        let started = Date()
        let data: Data
        let response: URLResponse
        do {
            (data, response) = try await URLSession.shared.data(for: request)
        } catch {
            let detail = Self.transportDetail(error)
            // ⚠ The URL is passed WHOLE and redacted inside `RKMLog.request` — the one place a URL is
            // made safe to log, so no call site can forget. (A later phase passes HLS playlist and
            // segment URLs through here; those carry a session token once B1–B3 lands.)
            RKMLog.request(correlation: correlation, method: method, url: url.absoluteString,
                           milliseconds: Self.milliseconds(since: started), error: detail, category: .net)
            throw APIError.transport(detail)
        }

        let elapsed = Self.milliseconds(since: started)
        let http = response as? HTTPURLResponse
        let status = http?.statusCode ?? 0
        RKMLog.request(correlation: correlation, method: method, url: url.absoluteString,
                       status: status, milliseconds: elapsed, bytes: data.count, category: .net)

        guard (200..<300).contains(status) else {
            let problem = http?.value(forHTTPHeaderField: "X-RKM-Auth-Problem")
            let envelope = try? JSONDecoder().decode(ErrorEnvelope.self, from: data)
            let message = envelope?.detail ?? Self.plainText(data)
            RKMLog.error("\(method) \(path) -> \(status)"
                            + (problem.map { " (auth problem: \($0))" } ?? "")
                            + (message.isEmpty ? "" : " — \(message)"),
                         category: .net, correlation: correlation)
            throw APIError.http(status: status, message: message, authProblem: problem)
        }

        return data
    }

    /// `NSError` domain/code plus its description — the thing that turns "it doesn't work" into a
    /// diagnosis (`apple/LOGGING.md` §3).
    private static func transportDetail(_ error: Error) -> String {
        let nsError = error as NSError
        // ⚠ `codes.isNotEmpty` rather than the code alone: a bare "(-1004)" with no domain reads as a
        // number, and `NSURLErrorDomain -1004` is the difference between a wrong address and a
        // TLS problem for whoever reads the log.
        return "\(type(of: error)) · \(nsError.domain) \(nsError.code) · \(nsError.localizedDescription)"
    }

    private static func plainText(_ data: Data) -> String {
        guard let text = String(data: data, encoding: .utf8) else { return "" }
        let single = text.replacingOccurrences(of: "\n", with: " ")
        return single.count > 300 ? String(single.prefix(300)) + "…" : single
    }

    private static func milliseconds(since start: Date) -> Int {
        max(0, Int(Date().timeIntervalSince(start) * 1000))
    }
}
